/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EWWISE_AUTODEFS_H
#define S3EWWISE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_WWISE_NAME "s3eWwise"
#define S3E_EXT_WWISE_HASH 0xe7657fff

#endif /* !S3EWWISE_AUTODEFS_H */
