/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "s3eWwise_autodefs.h"
#include "s3eEdk.h"
#include "s3eWwise.h"
//Declarations of Init and Term functions
extern s3eResult s3eWwiseInit();
extern void s3eWwiseTerminate();


void s3eWwiseRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[21];
    funcPtrs[0] = (void*)s3eWwiseMemoryMgrIsInitialized;
    funcPtrs[1] = (void*)s3eWwiseMemoryMgrTerm;
    funcPtrs[2] = (void*)s3eWwiseMemoryMgrInit;
    funcPtrs[3] = (void*)s3eWwiseStreamMgrCreate;
    funcPtrs[4] = (void*)s3eWwiseStreamMgrDestroy;
    funcPtrs[5] = (void*)s3eWwiseStreamMgrGetDefaultSettings;
    funcPtrs[6] = (void*)s3eWwiseSoundEngineIsInitialized;
    funcPtrs[7] = (void*)s3eWwiseSoundEngineInit;
    funcPtrs[8] = (void*)s3eWwiseSoundEngineGetDefaultInitSettings;
    funcPtrs[9] = (void*)s3eWwiseSoundEngineGetDefaultPlatformInitSettings;
    funcPtrs[10] = (void*)s3eWwiseSoundEngineTerm;
    funcPtrs[11] = (void*)s3eWwiseSoundEngineRenderAudio;
    funcPtrs[12] = (void*)s3eWwiseSoundEnginePostEvent;
    funcPtrs[13] = (void*)s3eWwiseSoundEngineRegisterGameObj;
    funcPtrs[14] = (void*)s3eWwiseSoundEngineUnregisterGameObj;
    funcPtrs[15] = (void*)s3eWwiseSoundEngineUnregisterAllGameObj;
    funcPtrs[16] = (void*)s3eWwiseSoundEngineLoadBank;
    funcPtrs[17] = (void*)s3eWwiseSoundEngineUnloadBank;
    funcPtrs[18] = (void*)s3eWwiseMusicEngineInit;
    funcPtrs[19] = (void*)s3eWwiseMusicEngineGetDefaultInitSettings;
    funcPtrs[20] = (void*)s3eWwiseMusicEngineTerm;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[21] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("s3eWwise", funcPtrs, sizeof(funcPtrs), flags, s3eWwiseInit, s3eWwiseTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eWwiseStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eWwiseRegisterExt;
    return 0;
}

int g_s3eWwiseVal = s3eWwiseStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eWwiseRegisterExt();
}
#endif

#endif
