#ifndef S3E_WWISE_AK_TYPES_FAKE_H
#define S3E_WWISE_AK_TYPES_FAKE_H

#include "s3eWwise.h"

/// Typedef which is used to allow importing the .h file that is generated by Wwise
typedef s3eWwiseUniqueID AkUniqueID;

#endif